version: 2
jobs:
  build:
    working_directory: ~/data-journal
    docker:
      - image: circleci/ruby:2.6-node
        environment:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: root
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: data_journal_test
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-{{ .Environment.CIRCLE_STAGE }}-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-{{ .Environment.CIRCLE_STAGE }}-dependencies
      - run:
          name: Install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-{{ .Environment.CIRCLE_STAGE }}-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Wait for database
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Setup database
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load
      - run:
          name: Run tests
          command: bundle exec rails test
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
