# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  aws_region: us-east-1
  aws_s3_bucket: <%= ENV["AWS_S3_BUCKET"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  redis_url: <%= ENV["REDIS_URL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  smtp_address: smtp.mandrillapp.com
  smtp_username: <%= ENV["MANDRILL_USERNAME"] %>
  smtp_password: <%= ENV["MANDRILL_API_KEY"] %>

development:
  <<: *default
  secret_key_base: ff1eb6fe2add6adecc00f865a638492ef4114ab4c50fb6f36213ea8742e6efaf1978729131f2f3db5412e81229831d52baf7050db0a22755e41c29368fc97de6

test:
  <<: *default
  secret_key_base: de65514f352a8954ff4c6e664964fde688a70135f13d1d673ae92eed4f3216c1e81a133adad6dcc49226c0bcb1e8effa09fdd6d13a012f5d138364e1627c5b91

staging:
  <<: *default

production:
  <<: *default
